### ISSUE TITLE
How to migrate JIRA source field - "resolution"?

### ISSUE THREAD

**Issue by johnwanng** [solidify/jira-azuredevops-migrator#831] opened 2023-08-21 06:29 UTC
**Describe the problem**
May I ask how to migrate the **Jira** source field  - "resolution"?

This is the section of the **json** where the **JIRA** source field - "resolution" is being referenced:

{
        "source": "resolution",
        "target": "Microsoft.VSTS.Common.ResolvedReason",
        "mapping": {
          "values": [
			{
              "source": "Done",
              "target": "Fixed"
            },
            {
              "source": "Won't Do",
              "target": "Deferred"
            },
            {
              "source": "Duplicate",
              "target": "Duplicate"
            },
            {
              "source": "Cannot Reproduce",
              "target": "Cannot Reproduce"
            },
            {
              "source": "By Design",
              "target": "As Designed"
            },
            {
              "source": "Closed",
              "target": "Fixed and verified"
            },
            {
              "source": "Deferred",
              "target": "Deferred"
            },
            {
              "source": "None",
              "target": "Deferred"
            },
			{
              "source": "Unresolved",
              "target": "Deferred"
            },
            {
              "source": "Not a Defect",
              "target": "Will not Fix"
            }		
          ]
        }
      },

And the **Microsoft.VSTS.Common.ResolvedReason** was not even inside **export** file after the **jira-export** command has been executed. Please advise if there is any syntax error or anything which you can see is not quite right, thank you for your assistance

**Comment by Alexander-Hjelm** [comment] 2023-08-21 07:34
See https://github.com/solidify/jira-azuredevops-migrator/issues/270 maybe? :)

**Comment by johnwanng** [comment] 2023-08-21 07:57
Hi Alex,

#270 does not help or work. Since the value of the **Microsoft.VSTS.Common.ResolvedReason** was not in the **export** file, the **Resolution** Jira field did not get migrated across, do you have any idea, thanks?

**Comment by Alexander-Hjelm** [comment] 2023-08-21 08:28
What happens if you omit the mapper? Just do:

```json
      {
        "source": "resolution",
        "target": "Microsoft.VSTS.Common.ResolvedReason"
      },
```

Does the Microsoft.VSTS.Common.ResolvedReason field appear in your exported issue .json files at all?

**Comment by johnwanng** [comment] 2023-08-21 08:32
No trace of "**Microsoft.VSTS.Common.ResolvedReason**" in the file.

**Comment by johnwanng** [comment] 2023-08-21 08:40
Hi Alex,

Have you been successfully migrated the **JIRA**'s **Resolution** field across to **DevOps** in the past?

**Comment by Alexander-Hjelm** [comment] 2023-08-21 08:45
You are correct here. I reviewed the code and it turns out that the `resolution` field is not actually exposed for mapping.

I will upload a fix for this ASAP and give you a build that you can try. Stand by for now :)

**Comment by johnwanng** [comment] 2023-08-21 08:47
Thank you for your assistance

**Comment by Alexander-Hjelm** [comment] 2023-08-21 08:55
[JiraExport-feature-resolution-mapping.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12394207/JiraExport-feature-resolution-mapping.zip)

Try this build of `JiraMigrator.exe` instead and let me know if this solves your issue!

**Comment by johnwanng** [comment] 2023-08-21 09:01
I will try that tomorrow, thank you Alex.

**Comment by Alexander-Hjelm** [comment] 2023-08-21 09:03
Perfect. I will hold off merging the feature until you can confirm that the issue is fixed :)

**Comment by johnwanng** [comment] 2023-08-22 01:24
Hi Alex,

There is no **Jiramigrator.exe** inside your zip file. I have instead tried with the **jira-export** command but after running it, there is still no **ReferenceName** of **Microsoft.VSTS.Common.ResolvedReason** in the export file hence, I think, the **Resolution** field might not have been not exported across.

I have even tried with both versions below in specifying the **resolution** Jira source field in the **json** file but they both failed meaning there is no **ReferenceName** of **Microsoft.VSTS.Common.ResolvedReason** in the export file after running the **jira-export** command. 

**First Version**
{
        "source": "resolution",
        "target": "Microsoft.VSTS.Common.ResolvedReason"
}


**Second Version**
{
        "source": "resolution",
        "target": "Microsoft.VSTS.Common.ResolvedReason",
        "mapping": {
          "values": [
			{
              "source": "Done",
              "target": "Fixed"
            },
            {
              "source": "Won't Do",
              "target": "Deferred"
            },
            {
              "source": "Duplicate",
              "target": "Duplicate"
            },
            {
              "source": "Cannot Reproduce",
              "target": "Cannot Reproduce"
            },
            {
              "source": "By Design",
              "target": "As Designed"
            },
            {
              "source": "Closed",
              "target": "Fixed and verified"
            },
            {
              "source": "Deferred",
              "target": "Deferred"
            },
            {
              "source": "None",
              "target": "Deferred"
            },
			{
              "source": "Unresolved",
              "target": "Deferred"
            },
            {
              "source": "Not a Defect",
              "target": "Will not Fix"
            }		
          ]
        }
      }

**Comment by Alexander-Hjelm** [comment] 2023-08-22 05:45
Try this build instead. I cleared the output folder to make sure that the build files were regenerated:

[Debug.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12405194/Debug.zip)

Check both Debug and Release. Inside there is an executable called **jira-export.exe** that you can use just like normal.

It seems that for me the resolution field is mapped correctly.

Here is an example of a created file:

```json
    {
      "Author": "5dc52a54b8eb490c677a56dd",
      "Time": "2020-04-30T12:29:06.192+02:00",
      "Index": 6,
      "Fields": [
        {
          "ReferenceName": "Microsoft.VSTS.Common.ResolvedReason",
          "Value": "Done"
        },
        {
          "ReferenceName": "System.State",
          "Value": "Resolved"
        }
      ],
      "Links": [],
      "Attachments": [],
      "Commit": null,
      "AttachmentReferences": false
    }
```

And here is my field mapping:

```json
{
  "source": "resolution",
  "target": "Microsoft.VSTS.Common.ResolvedReason"
},
```

**Closed** 2023-08-22 13:00 UTC
Labels: support
