### ISSUE TITLE
Unauthorized error while exporting work items from jira.

### ISSUE THREAD

**Issue by Akhithareddy** [solidify/jira-azuredevops-migrator#126] opened 2019-11-19 11:17 UTC
Hi,
we are using on premises jira server.i want to migrate work items from jira to azure devops.I installed migration tool by solidify team and I ran export command like Example: jira-export.exe -u p.rombouts@yourdomain.com -p XXXXX  --url https://yourinstance.atlassian.net --config config.json --force.
I'm getting below error and is this issue is due to lack of api token?
we don't have api tokens for on premises jira server.
=====================================
Copyright (c) Solidify
[I][16:34:01] Connecting to Jira...
[I][16:34:01] Retrieving Jira fields...
[E][16:34:02] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Response Content: <html>

<head>
    <title>Unauthorized (401)</title>

<script type="text/javascript">var contextPath = '';</script>
<script>
window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\"\"";
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-rest:web-resource-manager.resource-base-url-pattern"]="\"(?:(?:/s/.*?/_)?/download)\"";
WRM._unparsedData["jira.webresources:feature-flags.feature-flag-data"]="{\"enabled-feature-keys\":[\"nps.survey.inline.dialog\",\"jira.frother.reporter.field\",\"jira.plugin.devstatus.phasetwo\",\"atlassian.rest.xsrf.legacy.enabled\",\"jira.issue.status.lozenge\",\"com.atlassian.jira.config.PDL\",\"jira.plugin.devstatus.phasetwo.enabled\",\"atlassian.aui.raphael.disabled\",\"applinks.v3.ui\",\"frother.assignee.field\",\"app-switcher.new\",\"com.atlassian.jira.projects.ProjectCentricNavigation.Switch\",\"com.atlassian.jira.config.CoreFeatures.LICENSE_ROLES_ENABLED\"],\"feature-flag-states\":{\"jira.issue.search.jql.timing.databaseprimary\":false,\"jira.feature.flag.board\":false,\"jira.shared.portalpage.search.databaseprimary\":false,\"jira.shared.portalpage.search.indexprimary\":false,\"jira.instrumentation.laas\":false,\"jira.shared.searchrequest.database.search\":false,\"jira.issue.search.jql.timing.indexprimary\":false,\"jira.shared.portalpage.search.indexonly\":true,\"jira.create.linked.issue\":true,\"jira.issue.search.jql.timing.indexonly\":true}}";
WRM._unparsedData["jira.webresources:default-comment-security-level.DefaultCommentSecurityLevelHelpLink"]="{\"extraClasses\":\"default-comment-level-help\",\"title\":\"Commenting on an Issue\",\"url\":\"https://docs.atlassian.com/jira/jcore-docs-071/Commenting+on+an+Issue#Default-Comment-Security-Level\",\"isLocal\":false}";
WRM._unparsedData["com.atlassian.jira.project-templates-plugin:project-templates-plugin-resources.ptAnalyticsData"]="{\"instanceCreatedDate\":\"2012-07-31\"}";
WRM._unparsedData["jira.webresources:dateFormatProvider.dateFormat"]="{\"meridiem\":[\"AM\",\"PM\"],\"eras\":[\"BC\",\"AD\"],\"months\":[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"],\"monthsShort\":[\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sep\",\"Oct\",\"Nov\",\"Dec\"],\"weekdaysShort\":[\"Sun\",\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\",\"Sat\"],\"weekdays\":[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"]}";
WRM._unparsedData["com.atlassian.pocketknife.featureflags-plugin:pocketknife-feature-flags.feature-flag-data"]="{\"enabled-feature-keys\":[\"nps.survey.inline.dialog\",\"jira.frother.reporter.field\",\"jira.plugin.devstatus.phasetwo\",\"atlassian.rest.xsrf.legacy.enabled\",\"jira.issue.status.lozenge\",\"com.atlassian.jira.config.PDL\",\"jira.plugin.devstatus.phasetwo.enabled\",\"atlassian.aui.raphael.disabled\",\"applinks.v3.ui\",\"frother.assignee.field\",\"app-switch

Can somebody help me out on this.

**Comment by madkoo** [comment] 2019-11-20 08:04
@Akhithareddy were you able to get this working? Can you take a look at #3 and #23 issues which are related to see if you can get the authorization working?

**Comment by Akhithareddy** [comment] 2019-11-20 09:21
@madkoo Issue 3 is related to jira cloud.
we are using jira server ,But in JIRA Server instance dont know from where to get API Token.
what permissions  do we require to export work items from jira.
I'm having administrator access.

**Comment by madkoo** [comment] 2019-11-20 09:31
@Akhithareddy  sorry, the second issue had a wrong reference number. It should have been #22 
Instead of email, did you try using username?

**Comment by Akhithareddy** [comment] 2019-11-20 10:29
@madkoo im getting below error if I use username instead of mail id.
===============
[E][15:57:38] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html>
<html lang="en">
<head>

**Comment by Akhithareddy** [comment] 2019-11-21 06:35
@MOlausson  Please find attached log file and config file used.
I ran Command line in the path where I extracted zip files of the tool.
Updated config file and users.txt file in the root and used command:
jira-export.exe -u jiraaccount@some.domain -p xxxxxxx --url https://my.jira.url --config config-scrum.json --force
[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3873079/config.txt)
[jira-export-log-191120-161621.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3873080/jira-export-log-191120-161621.txt)

**Comment by MOlausson** [comment] 2019-11-21 10:22
Thanks @Akhithareddy. Can you try this using just your username for logging, i.e. jira-export.exe -u jirauser -p xxxxxxx --url https://my.jira.url --config config-scrum.json --force?

**Comment by Akhithareddy** [comment] 2019-11-21 10:44
I tried with username but getting error as
===================
Copyright (c) Solidify
[I][16:09:41] Connecting to Jira...
[I][16:09:42] Retrieving Jira fields...
[E][16:09:43] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html>
<html lang="en">
<head>

**Comment by Akhithareddy** [comment] 2019-11-25 06:19
@MOlausson @madkoo Any update regarding json response not found error.
i'm using jira on premises tool of 8.5.1 version. Is it any version conflict or request issue.

**Comment by runerasmussen** [comment] 2019-11-25 15:38
I am experiencing the same issue with Unauthorized (401) upon retrieval of Jira fields, after initial succesful connection to Jira.
I run Jira Server v8.4.2#804003 on port 8443.

Online 238 in the attached log file it reads:
Basic Authentication Failure - Reason : AUTHENTICATED_FAILED

Command used:
C:\a\Jira til Azure DevOps migrering\jira-azuredevops-migrator-2.2.59>jira-export -u jiraaccount@mydomain.com -p XXXXX --url https://jira.mydomain.com:8443 --config config-scrum.json --force

And here is the log file:
[jira-export-log-191125-162511.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3887343/jira-export-log-191125-162511.txt)

I hope you can find the culprit... please let me know if I can help.

**Comment by Akhithareddy** [comment] 2019-11-26 05:47
@runerasmussen when I tried with user name i'm not receiving authentication error but getting below error json response not found.could you please help on this.
Jira Exporter v2.2.59
Copyright (c) Solidify
[I][12:51:28] Connecting to Jira...
[I][12:51:28] Retrieving Jira fields...
[E][12:51:29] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html>
<html lang="en">
<head>

**Comment by runerasmussen** [comment] 2019-11-26 09:01
@Akhithareddy, great tip to use username only, without domain. It seems to work for me, and the export is spinning...

**Comment by madkoo** [comment] 2019-11-26 09:10
@runerasmussen  sorry for my late reply, but indeed you should use username without a domain.
Good to hear that it worked for you.
@Akhithareddy, I tried to repro this by setting up a local Jira server 8.5.1 and did a migration using username in the command. The migration ran successfully.
 Examining the log file you sent, it still seems you are getting an authorization exception.
Have you checked if the user you are using in the command has access to that project?

**Comment by MOlausson** [comment] 2019-12-02 09:12
@Akhithareddy any update on this? It's often a permission related issue so we cannot reproduce. We'll close this issue soon, feel free to reach out again if you still have problems.

**Comment by ShadowXVII** [comment] 2019-12-03 00:42
This has caused us the same issue but for Atlassian Cloud. The username can't be without a domain or otherwise it wouldn't authenticate. Using API Keys as the password.

This didn't occur in the previous versions, so it's a recent change. 

```
[I][11:39:58] Connecting to Jira...
[I][11:39:59] Retrieving Jira fields...
[I][11:39:59] Retrieving Jira link types...
[E][11:40:00] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: **Response Status Code: 400**. Response Content: {"errorMessages":["The value 'XX' does not exist for the field 'project'.","Field 'type' does not exist or this field cannot be viewed by anonymous users.","Field 'resolution' does not exist or this field cannot be viewed by anonymous users.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
```

**Comment by Akhithareddy** [comment] 2019-12-03 05:11
@runerasmussen @madkoo I have project administrator access, But still getting authorization error.

**Comment by madkoo** [comment] 2019-12-09 13:12
@Akhithareddy  closing this now because we are unable to reproduce this problem, all seems to work as expected. As said before usually, these kinds of errors point to permission related issues.

**Closed by madkoo** 2019-12-09 13:12 UTC

**Comment by Ashish05178** [comment] 2019-12-20 03:06
Hi @Akhithareddy
I am aslo getting the same error.Can you please share how you resolved this.
Thanks

**Comment by ShadowXVII** [comment] 2020-01-14 01:38
I dug a little more into this. I think it's an issue with the Atlassian.SDK -- I'm running the project in VS to see if I can gather anymore information.

**Comment by ShadowXVII** [comment] 2020-01-14 02:59
Seems the request, specifically the Issue search is failing -- note the BadRequest response from Atlassian.SDK. 

- Tried removing maxResults but no change. 
- Tried changing search parameters, no change.
- Tried changing the project, no change.

It seems almost like an authentication issue? As if the API can't seem to find the projects? The credentials look like they're being passed via cookie though.

`"{\"errorMessages\":[\"The value 'FG' does not exist for the field 'project'.\",\"Field 'type' does not exist or this field cannot be viewed by anonymous users.\",\"Field 'resolution' does not exist or this field cannot be viewed by anonymous users.\"],\"warningMessages\":[]}"`

![image](https://user-images.githubusercontent.com/446329/72310053-d1db5380-36d4-11ea-9739-8a9dd8f7da25.png)
