### ISSUE TITLE
Exporting a revision with deleted resolution throws a NullReferenceException]

### ISSUE THREAD

**Issue by j8d** [solidify/jira-azuredevops-migrator#270] opened 2020-08-18 01:00 UTC
```
      {
        "source": "resolution",
        "source-type": "name",
        "target": "System.Reason",
        "mapping": {
          "values": [
            {
              "source": "Fixed",
              "target": "Fixed"
            },
...
```

When the resolution of work item is set to null at some point in the history of the item, that revision throws an NRE.

[D][20:47:50]    Mapping revision 6.
[E][20:47:50] Error mapping field 'System.Reason' on item 'XXX-50691'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraMapper.<>c__DisplayClass21_0.<MapValue>b__2(Value s) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 494
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.MapValue(JiraRevision r, String itemSource) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 494
   at JiraExport.JiraMapper.<>c__DisplayClass16_0.<InitializeFieldMappings>b__0(JiraRevision r) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 331
   at JiraExport.JiraMapper.MapFields(JiraRevision r) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 279:
   at JiraExport.JiraMapper.<>c__DisplayClass21_0.<MapValue>b__2(Value s) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 494
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.MapValue(JiraRevision r, String itemSource) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 494
   at JiraExport.JiraMapper.<>c__DisplayClass16_0.<InitializeFieldMappings>b__0(JiraRevision r) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 331
   at JiraExport.JiraMapper.MapFields(JiraRevision r) in C:\J2A_build\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 279

AB#5955

**Comment by madkoo** [comment] 2020-09-09 11:52
@j8d We will look into this.

**Comment by MuthumariPonnusamy** [comment] 2022-07-06 16:58
@madkoo Could you please let me know any fix is given for this issue. I'm also getting a same error message.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraMapper.<>c__DisplayClass21_0.<MapValue>b__2(Value s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.MapValue(JiraRevision r, String itemSource)
   at JiraExport.JiraMapper.<>c__DisplayClass16_0.<InitializeFieldMappings>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r):
   at JiraExport.JiraMapper.<>c__DisplayClass21_0.<MapValue>b__2(Value s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.MapValue(JiraRevision r, String itemSource)
   at JiraExport.JiraMapper.<>c__DisplayClass16_0.<InitializeFieldMappings>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)

**Comment by Alexander-Hjelm** [comment] 2022-09-04 11:47
I have been unable to reproduce this issue. Can neither set resolution to null via the web or via REST API.

@j8d, @MuthumariPonnusamy. Can you elaborate on the repro steps? How did you manage to set the "resolution" field to null?

**Comment by MuthumariPonnusamy** [comment] 2022-09-05 11:40
Hi, for 'Assigned to' field below is the config file but while exporting the work item assigned to value is not exported in the json file but in jira this fields holds the value.

{
        "source": "assignee",
	"source-type": "name",
        "target": "System.AssignedTo",
        "mapper": "MapUser",
        "mapping": {
          "values": [{
              "source": "a028608",
              "target": "balamurugan.e@volvo.com"
            },
]
}

Can you please suggest us what we can do in this.

**Comment by Alexander-Hjelm** [comment] 2022-09-05 12:09
@MuthumariPonnusamy You support question in unrelated to this bug, please create a new Issue :)

**Closed** 2023-05-20 11:02 UTC
Labels: bug
