### ISSUE TITLE
Migrating multiple JIRA projects at once to azure DevOps 

### ISSUE THREAD

**Issue by jdewa** [solidify/jira-azuredevops-migrator#457] opened 2022-05-19 15:06 UTC
Just wanted to know if it is possible to migrate multiple JIRA projects at once using the configuration JSON file to azure DevOps u

**Comment by Alexander-Hjelm** [comment] 2022-05-20 09:47
Duplicate of #456 , closing

**Closed by Alexander-Hjelm** 2022-05-20 09:47 UTC
Labels: support
