### ISSUE TITLE
MIgrating Test Cases with test steps and expected result

### ISSUE THREAD

**Issue by nipanesanjay** [solidify/jira-azuredevops-migrator#172] opened 2020-01-15 06:59 UTC
Hi,

I want to migrate test cases with test steps and expected result.

I did the configuration and migrated test cases but those are getting migrated without test steps.

Please advise.

**Comment by MOlausson** [comment] 2020-01-18 07:50
Hi @nipanesanjay, 

This is expected behaviour, currently we only support exporting the built-in Jira issue types. We're looking at options to export 3rd party data as well, what testing tool are you using?

Mathias

**Comment by nipanesanjay** [comment] 2020-01-20 07:40
Thanks for the updates. We are using Azure DevOps for creating our test cases.

**Comment by MOlausson** [comment] 2020-01-20 07:47
@nipanesanjay got it. And what extension (if any) are you using in Jira? I assume some 3rd party since the steps doesn't migrate.

**Comment by nipanesanjay** [comment] 2020-01-20 08:17
In JIRA test cases has been created using Zephyr Test.

**Comment by kmuthukumar-rp** [comment] 2020-01-21 17:30
@MOlausson @nipanesanjay If it helps any, you would need to hit Zephyr API to get the test steps values. Currently the way I had dealt with it is:  In JiraItem.ExtractFields(), for teststep issuetype and customfield teststep, download and transform the test steps values into an array of objects by hitting the Zephyr API `rest/zapi/latest/teststep/{issueId}.` We might be able to write a mapper to map teststeps, but I couldnt get it to working, so did it this way.

Then save the test step values for each test at the end of ImportCommandLine.ExecuteMigration by maintaining an array of wi.Id's when test item gets created (only once, not for every revision) and then process them at the end. 

> First get the saved TestCase by,

            ```
var testService = Collection.GetService<ITestManagementService>();
            var testProject = testService.GetTeamProject(_project);
            ITestCase testCase = testProject.TestCases.Find(wiId);
            return testCase;
```

> Then AttachSteps and save:

```
ITestStep step = testCase.CreateTestStep();
step.Title = stepTitle;
 step.Description = stepTitle;
step.ExpectedResult = stepElement.Element(Constants.TESTSTEP_RESULT).Value;
testCase.Actions.Add(step);
```
I am still missing to get teststep attachments which is avl with the API call: `/rest/zapi/latest/attachment/{fileid}`. Anyways, I am still not able to complete to do a PR and contribute. But hope this gives a headstart and helps in someway.

**Comment by sanjeev40084** [comment] 2020-02-08 22:42
@MOlausson we are migrating JIRA project to Azure DevOps currently and some of the JIRA projects have 1000+ tests in Zephyr. If this is implemented in the tool, this will definitely save us lot of time during our migration.

**Comment by shyamprasadbandi** [comment] 2020-04-21 05:38
This implementation would help me as well, we have similar migration plans.

**Comment by rsikr** [comment] 2020-05-13 21:51
Hi @MOlausson, Do we have any update on this please?

**Comment by pengliangyou** [comment] 2023-04-26 06:38
> @kmuthukumar-rp Hello, please share the full code of JiraItem.cs file where the Zephyr API is used to extract data.

@PrashantRanjanTR @kmuthukumar-rp hi do you have the code to extract data ?  i faced the same issue about steps. 
Thanks very much!

**Comment by Alexander-Hjelm** [comment] 2023-04-26 21:50
Zephyr test data is now part of our Pro offering. Let me know if this could be interesting for you and I can send you a quote :)
________________________________

**Comment by Alexander-Hjelm** [comment] 2024-01-02 11:27
Closing as this feature is now a part of our Jira Migrator PRO offering

**Closed by Alexander-Hjelm** 2024-01-02 11:27 UTC
Labels: enhancement
