### ISSUE TITLE
Attachments are not mapping to azure devops 

### ISSUE THREAD

**Issue by sssparsh05** [solidify/jira-azuredevops-migrator#177] opened 2020-01-31 10:20 UTC
while doing import attachments are not mapping to azure devops all issues will left with no attachments.Any suggestion you have?

**Comment by madkoo** [comment] 2020-02-03 10:59
@sssparsh05 can you provide more information eg. the log of export? 
When you have exported your items are the attachments downloaded from jira ?

**Comment by sssparsh05** [comment] 2020-02-03 11:20
[wi-import-log-200118-160701.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4147579/wi-import-log-200118-160701.txt)
Yes Attachments are downloaded while export .
Logs attached

**Comment by madkoo** [comment] 2020-02-03 11:29
@sssparsh05  the log that you provided is an import, not an export log. 
Firstly I would advise you to re-check your config file because looking at the import log many items are not loaded by the tool. Looks to me like those files you are trying to import are faulty. 
Once you are sure the config looks good, run the export again, better yet, do a test run, pick one item in Jira which has attachments export that and try to import.

**Comment by sssparsh05** [comment] 2020-02-03 11:30
[jira-export-log-200118-111417.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4147609/jira-export-log-200118-111417.txt)
ok i will try for one item.

**Comment by sssparsh05** [comment] 2020-02-03 12:23
[jira-export-log-200203-174552.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4147831/jira-export-log-200203-174552.txt)
[wi-import-log-200203-174828.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4147832/wi-import-log-200203-174828.txt)

**Comment by sssparsh05** [comment] 2020-02-03 12:23
I tried with one item

**Comment by sssparsh05** [comment] 2020-02-03 12:24
i am using below config file
{
  "source-project": "CER",
  "target-project": "CER",
  "query": "project = CER AND issuetype = Sub-task AND status = Done AND description ~ Westward AND assignee in (esther.garcia1) ORDER BY priority DESC, updated DESC",
  "workspace": "C:\\Users\\u91205\\Downloads\\import\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "Agile",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Feature"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "User Story"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Feature,Epic,User Story,Bug",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Done",
              "target": "Resolved"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Removed",
              "target": "Removed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Removed",
              "target": "Removed"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.StoryPoints",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      },
      {
        "source": "environment",
        "source-type": "name",
        "target": "Microsoft.VSTS.TCM.SystemInfo",
        "for": "Bug,Epic"
      }
    ]
  }
}

**Comment by madkoo** [comment] 2020-02-03 12:58
Just for information, you are missing lot of mapping configuration as well, my suggestion is to fix that too otherwise you import will be done with incomplete data.

**Comment by madkoo** [comment] 2020-02-03 13:01
@sssparsh05  can you provde of of the exported items as well, so we can investigate why the tool fails to load the json file.

**Comment by sssparsh05** [comment] 2020-02-03 15:26
{
  "Type": "Product Backlog Item",
  "OriginId": "CER-220",
  "WiId": -1,
  "Revisions": [
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-01-30T14:56:20.013+05:30",
      "Index": 0,
      "Fields": [
        {
          "ReferenceName": "System.Title",
          "Value": "[CER-220] Operational Support Sprint 1"
        },
        {
          "ReferenceName": "System.AssignedTo",
          "Value": "roberto.enjuanes@wbadev.com"
        },
        {
          "ReferenceName": "System.Description",
          "Value": "<style>div {\r\n    display: block;\r\n}\r\n\r\ntable.confluenceTable {\r\n    border-collapse: collapse;\r\n    margin: 5px 0 5px 2px;\r\n    width: auto;\r\n}\r\n\r\ntable {\r\n    display: table;\r\n    border-collapse: separate;\r\n    border-spacing: 2px;\r\n    border-color: grey;\r\n}\r\n\r\ntbody {\r\n    display: table-row-group;\r\n    vertical-align: middle;\r\n    border-color: inherit;\r\n}\r\n\r\ntr {\r\n    display: table-row;\r\n    vertical-align: inherit;\r\n    border-color: inherit;\r\n}\r\n\r\nth.confluenceTh {\r\n    border: 1px solid #ccc;\r\n    background: #f5f5f5;\r\n    padding: 3px 4px;\r\n    text-align: center;\r\n}\r\n\r\nth {\r\n    font-weight: bold;\r\n    text-align: -internal-center;\r\n}\r\n\r\ntd, th {\r\n    display: table-cell;\r\n    vertical-align: inherit;\r\n}\r\n\r\n    td.confluenceTd {\r\n        border: 1px solid #ccc;\r\n        padding: 3px 4px;\r\n    }\r\n\r\ndfn, cite {\r\n    font-style: italic;\r\n}\r\n\r\n    cite:before {\r\n        content: \"\\2014 \\2009\";\r\n    }\r\n</style><p><b>User Story</b></p>\n\n<p>As an IT team member, I need to spend part of my office hours to support incidents and user requests that are urgent and outside the planned activities of the sprint.</p>\n\n<p> </p>\n\n<p><b>Additional Information</b></p>\n\n<p><font color=\"#de350b\">PLEASE NOTE</font>: Log incidents and unplanned activities as Sub-Tasks within this Story.  This way, we can estimate Story Points used for support that we use in each Sprint. Effort of this Story will be registered in the next Sprint planning session. Thanks.</p>"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": null
        },
        {
          "ReferenceName": "System.IterationPath",
          "Value": "Sprint 1 - Rhine Falls"
        },
        {
          "ReferenceName": "System.State",
          "Value": null
        }
      ],
      "Links": [
        {
          "Change": 0,
          "TargetOriginId": "CER-379",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        }
      ],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-01-30T14:56:20.98+05:30",
      "Index": 1,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-01-30T14:56:29.697+05:30",
      "Index": 2,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-01-30T14:56:29.847+05:30",
      "Index": 3,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-01-30T14:57:19.88+05:30",
      "Index": 4,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-01-30T21:07:53.077+05:30",
      "Index": 5,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "Deepu.Mohanan@boots.co.uk",
      "Time": "2019-01-31T16:15:15.403+05:30",
      "Index": 6,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-01T17:05:50.72+05:30",
      "Index": 7,
      "Fields": [
        {
          "ReferenceName": "System.State",
          "Value": null
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-01T17:05:52.4+05:30",
      "Index": 8,
      "Fields": [
        {
          "ReferenceName": "System.State",
          "Value": null
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-05T19:28:26.207+05:30",
      "Index": 9,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-05T19:30:41.803+05:30",
      "Index": 10,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-07T18:01:40.603+05:30",
      "Index": 11,
      "Fields": [
        {
          "ReferenceName": "System.State",
          "Value": null
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-11T20:15:50.37+05:30",
      "Index": 12,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-11T22:25:26.353+05:30",
      "Index": 13,
      "Fields": [
        {
          "ReferenceName": "System.State",
          "Value": null
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "Roman.Gerteis@wbadev.com",
      "Time": "2019-02-12T16:29:49.593+05:30",
      "Index": 14,
      "Fields": [
        {
          "ReferenceName": "System.State",
          "Value": null
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-26T23:19:24.49+05:30",
      "Index": 15,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "roberto.enjuanes@wbadev.com",
      "Time": "2019-02-27T17:27:42.33+05:30",
      "Index": 16,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "Roman.Gerteis@wbadev.com",
      "Time": "2019-03-09T22:43:21.787+05:30",
      "Index": 17,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    }
  ]
}

**Comment by sssparsh05** [comment] 2020-02-03 15:27
Above is exported item json. 
Attachments are exported but problem occuring while import it keet left unattached to all tickets

**Comment by madkoo** [comment] 2020-02-03 15:37
@sssparsh05 can you attach the entire json file instead of  copying the content of the file otherwise is kind of hard to say if the faile is broken for some reason.

**Comment by sssparsh05** [comment] 2020-02-03 15:42
[CER-220.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4148697/CER-220.txt)
[CER-252.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4148703/CER-252.txt)

**Comment by sssparsh05** [comment] 2020-02-03 15:42
Attached

**Comment by madkoo** [comment] 2020-02-03 16:08
@sssparsh05 just to be sure, can you confirm that from the exported issue CER-252, when you open that file and search for the first attachment "Filepath" then does the image, it is pointing to, exists?
   
Otherwise, the exported issue file seems to be correct and the only thing I can think of at the moment is that the path where it is pointing for the attachment does not exist.
Maybe try to change the "workspace" path in the config.json to eg. C:\Temp or what you prefer and export CER-252 item again. Then you can verify that the Attachment folder is created and the two attachments that the issue contains are there. If everything looks fine do the import.

**Comment by sssparsh05** [comment] 2020-02-04 09:31
i have checked the path it is accessible and correct no issues with that.
Any where we need to define in config file for attachment to attach while import?

**Comment by sssparsh05** [comment] 2020-02-06 09:07
Can you provide your config file here so i can see it ?

**Comment by madkoo** [comment] 2020-02-07 08:32
@sssparsh05  The only path you can configure is the Workspace path. 
You can find our sample configs here:  [Configuration documentation](https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md)

**Comment by madkoo** [comment] 2020-02-25 13:51
Closing this issue in lack of further response. @sssparsh05  feel free to reopen if you still experience problems

**Comment by sssparsh05** [comment] 2020-03-05 10:32
Here is my config file attached.
I have tried many ways but still attachments are importing.

**Comment by madkoo** [comment] 2020-05-28 12:52
@sssparsh05 closing issue due unable to reproduce. Hope you have resolved the problem you had.
Feel free to contact us for help if needed

**Closed by madkoo** 2020-05-28 12:52 UTC
