### ISSUE TITLE
Images not appearing in ADO Text (multiple lines) field after import.

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#510] opened 2022-08-05 11:54 UTC
I have two Text (multiple lines) fields in my Bug WIT.  Only one of the fields is rendering the images correctly after the import. The images themselves are being migrated to ADO and appear in the Attachments tab as expected (Screenshot 3) but for some reason the image is not showing in one of the fields.

I have also manually attached the image to this field and that works as expected.

I have also realised that there are other issues raised that refer to spaces in the name of the Jira attachments but the files I am using don't have spaces but hyphens. (Screenshot 4)

The two fields are:

Microsoft.VSTS.TCM.ReproSteps - works as expected (Screenshot 1)

Custom.FixedDescription - text renders correctly but it does not render the image correctly after import.  When it is done manually it works as expected. (Screenshot 2)

Below is the mapping config:

{
        "source": "Fixed Description",
	"source-type": "name",
	"target": "Custom.FixedDescription",
	"mapper": "MapRendered"
      },

{
        "source": "Description",
	"source-type": "name",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
	"mapper": "MapRendered"
      }

Screenshot 1

![image](https://user-images.githubusercontent.com/92213401/183071451-e19fbece-4c9b-4e0b-8daa-9322850ff953.png)

Screenshot 2

![image](https://user-images.githubusercontent.com/92213401/183071567-f077b4a2-3fda-40ef-9250-6f1547cbd2a0.png)

Screenshot 3

![image](https://user-images.githubusercontent.com/92213401/183071991-2b6d4b0a-5e23-493a-8e24-1f7e2b315418.png)

Screenshot 4

![image](https://user-images.githubusercontent.com/92213401/183111448-b9ec6731-d996-4a00-bca7-dfda1b61f6b1.png)

When I right click on the images in ADO using the Copy image address option the 2 images have different paths:

https://dev.azure.com/jira/xxxxx/attachment/61393/61393_image-2021-02-08-11-34-26-465.png

https://dev.azure.com/Ikonxxxx/a26a5a50-a0a5-455c-8cb6-b61f1fb13ea8/_apis/wit/attachments?FileID=9974867&FileName=image-2019-10-08-15-56-33-424.png

Image ending in 465.png is the one not displaying correctly.

Any help with this will be greatly appreciated.

Chris

**Comment by Alexander-Hjelm** [comment] 2022-08-09 07:01
Not 100% sure what is happening. The Importer has some logic for converting html img-tags to the correct format. Probably something funky is going on under the hood. You could try either:
- Experiment with the faulty image url and try to get it on a correct format. See if the image manages to load. If it does, you could write a custom rest api script that updates the description of each bug in the project and transforms the image urls.
- Clone the latest version of the jira-azuredevops-migrator repo, build the tool yourself and try migrating with that version. We have merged some bugfixes related to the image tag mapper, so it could be that the issue is already resolved, but not yet released :)

**Comment by C-F-Palmer** [comment] 2022-08-16 17:07
Hi Alexander,

Sorry for the slow reply I have been on holidays! Thanks very much for your response. Unfortunately I have been having trouble compiling the latest code and was wondering when the next release might be? If it is soon I can wait but if not is it possible to get a new zip with the latest version to see if the fix is in?

Thanks

Chris

**Comment by C-F-Palmer** [comment] 2022-08-18 17:30
Hi Alexander,

I have mange to get the latest code to run however it seems to doing something with the images that is not ideal.

The images are coming over now with the full path of the file and name:

![image](https://user-images.githubusercontent.com/92213401/185456405-44d4a653-f998-4dec-b112-f2b1e1adbd10.png)

As you can see it is using the export path for the attachments.

Also neither image is appearing in the assigned fields in ADO:

![image](https://user-images.githubusercontent.com/92213401/185457612-57d95135-afb0-412d-9306-a3c36179db09.png)

One other observation from the latest code is that I get an exception if a field is set to required in ADO where as in the current release version this is not a problem.

Thanks

Chris

**Comment by Alexander-Hjelm** [comment] 2022-08-21 17:23
That's probably a bug. It sounds like both issues are related to the TFS work item api client. I'll make it a point to look at it sometime in the upcoming week. I'll contact you if I need any clarifications on the repro step :)

**Comment by Alexander-Hjelm** [comment] 2022-09-28 07:29
Sorry for the wait @C-F-Palmer. Can you check if your problem has been resolved in the latest prerelease? :)

You can find a download here:
[jira-azuredevops-migrator-3.0.15.zip](https://github.com/solidify/jira-azuredevops-migrator/files/9662494/jira-azuredevops-migrator-3.0.15.zip)

**Comment by C-F-Palmer** [comment] 2022-10-10 15:50
Hi Alexander,

I have taken the latest build 3.0.15 but it doesn't seem to be importing the issues to Azure correctly. I am getting the following error message:
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TF401326: Invalid field status 'ReadOnly' for field 'System.BoardColumn'.

The WIT I am importing to does not use the System Board field.

Although it seems to import, it is not importing any fields except for the work item title and uses "Placeholder Name":

![image](https://user-images.githubusercontent.com/92213401/194904973-2cf01751-6949-4e10-9a41-64009670c497.png)

Also one of the images is being duplicated:

![image](https://user-images.githubusercontent.com/92213401/194905589-77314f02-c5cc-4aa4-9b4c-c765ac5aeb1d.png)

**Comment by grvs08** [comment] 2022-10-23 20:53
I am having a similar issue in the Description field (System.Description ). Any resolution for this issue?

**Closed** 2022-10-25 13:30 UTC
Labels: bug
