### ISSUE TITLE
Revisions trying to save System.BoardColumn related updates causes exception

### ISSUE THREAD

**Issue by omustapasa** [solidify/jira-azuredevops-migrator#568] opened 2022-10-07 13:24 UTC
**Describe the problem**
During the import, there are revisions which alter the System.State information on a work item.
After the initial revision is created (which already has System.State information available on it?), other revisions are being executed.

Since there are revisions which change the System.BoardColumn; upon the initial Revision the field is ''ReadOnly'' hence any future save operation or update operation results in an AggregationException and work item history is migrated incomplete.
As a result, you will be missing all relevant history with and after the exception for a given ticket.

"TF401326: Invalid field status 'ReadOnly' for field 'System.BoardColumn"

Does the information for System.BoardColumn etc needs to be saved with each update where the API throws an exception for already existing items saying its Readonly?

**To Reproduce**
1. Export a JIRA work item which has state changes, comments, attachments and custom fields information on it.
2. Migrate exported items
3. Revisions are not fully migrated

**Tool version**
 - Version of the jira-azuredevops-migrator tool latest master

**Comment by omustapasa** [comment] 2022-10-07 13:35
Might be quite hacky but below snipped helps when placed inside SaveWorkItemFields() before related items are added to patchDocument object.

After migration I can see work items on ADO being assigned to correct columns and moving along with their respective statuses on the board.

`if (wi.Id.HasValue && key.Contains("BoardColumn"))
 continue;`

**Comment by Alexander-Hjelm** [comment] 2022-10-07 13:39
Ok! I'll try your fix as soon as I have time, Probably sometime next week

**Comment by omustapasa** [comment] 2022-10-07 19:16
You might like to add 
`if (wi.Id.HasValue && patchDocument.Any()){ ... }` before calling the `                    _witClientWrapper.UpdateWorkItem(patchDocument, wi.Id.Value);
`
to prevent an unnecessary call.

**Comment by Alexander-Hjelm** [comment] 2022-10-18 16:43
Duplicate of https://github.com/solidify/jira-azuredevops-migrator/issues/572. PR is created, and discussion will continue in https://github.com/solidify/jira-azuredevops-migrator/issues/572

**Closed by Alexander-Hjelm** 2022-10-18 16:43 UTC
Labels: bug
