### ISSUE TITLE
Custom Field Value export empty value

### ISSUE THREAD

**Issue by Jyu142** [solidify/jira-azuredevops-migrator#290] opened 2020-10-15 04:17 UTC
The values are similiar to JIRA labels.
![image](https://user-images.githubusercontent.com/56811003/96072433-4ca6ea00-0e72-11eb-8888-f6dce387dfbb.png)
![image](https://user-images.githubusercontent.com/56811003/96072250-e7eb8f80-0e71-11eb-88b3-12f4b4126d31.png)
when using the PS Jira query, it displays that there is indeed a value inside of it
![image](https://user-images.githubusercontent.com/56811003/96072487-65170480-0e72-11eb-9f6c-83dbaca1ca22.png)
however, when i use the exporter using the config:
![image](https://user-images.githubusercontent.com/56811003/96072933-6137b200-0e73-11eb-8862-311a2de1e005.png)
which has MayArray, or without, it displays as null
![image](https://user-images.githubusercontent.com/56811003/96072953-6d237400-0e73-11eb-88b6-e1f6078af7ea.png)
when i use it without a mapper and with source type:
![image](https://user-images.githubusercontent.com/56811003/96073344-40239100-0e74-11eb-8712-e201df9f8d74.png)
it is displayed as an empty value "":
![image](https://user-images.githubusercontent.com/56811003/96073370-516c9d80-0e74-11eb-8c34-941e97660625.png)
I have used GET method to extract the json of the jira field and it seems to be a single string array:
![image](https://user-images.githubusercontent.com/56811003/96073423-6b0de500-0e74-11eb-8148-ef0ccd2d846a.png)
when i map it similar to tags:
![image](https://user-images.githubusercontent.com/56811003/96074177-081d4d80-0e76-11eb-96bf-9c2988b86420.png)
I am still getting null value:
![image](https://user-images.githubusercontent.com/56811003/96074187-0fdcf200-0e76-11eb-957c-fb614c4e1d08.png)

additionally, for source types, im getting:
"" for **key, label, labels, value,custom,custom_value,**
it doesn't come out for **name**

How should i proceed with this?
Thank you!

**Comment by MOlausson** [comment] 2020-10-16 17:51
Thanks for the detailed description @Jyu142, we'll investigate.

**Comment by Urglefloggah666** [comment] 2020-11-09 22:17
I am having a similar issue with mapping checkbox lists, please see below:
config:
![image](https://user-images.githubusercontent.com/20916516/98602975-67fffa80-2335-11eb-9e3e-21f9cb6d7e16.png)
JIRA fields:
![image](https://user-images.githubusercontent.com/20916516/98603011-7d752480-2335-11eb-822c-113d6726f53a.png)
export:
![image](https://user-images.githubusercontent.com/20916516/98603045-8960e680-2335-11eb-88fb-9c0986f567ab.png)

as you can see, when the field has a single checkbox value, it exports fine, but multiple values seem to break.

**Comment by Alexander-Hjelm** [comment] 2021-12-06 12:48
Duplicate of issue #374, contd there

**Closed by Alexander-Hjelm** 2021-12-06 12:48 UTC
