### ISSUE TITLE
Attatchment referenced in description causes errors 

### ISSUE THREAD

**Issue by dbssbu** [solidify/jira-azuredevops-migrator#1084] opened 2024-12-20 13:39 UTC
**Describe the problem**

The field System.Description is placed always in revision index 0 with the latest content from jira.
If an attatchment image is referenced in the 'System.Description' field, the image may not be available when importing rev 0.

The image may not be available at this time, because it is added later.
This is caused, because the export writes the latest description content at revision index 0
This causes failures during the import, because wi-import can't save the rev 0 correctly.

**To Reproduce**

1. place PRD-1847.json file in a folder called PRO
```
{
  "Type":  "Task",
  "OriginId":  "PRO-1847",
  "WiId":  -1,
  "Revisions":  [
    {
      "Author":  "my.name@domain.de",
      "Time":  "2020-07-08T10:22:59+02:00",
      "Index":  0,
      "Fields":  [
        {
          "ReferenceName":  "System.Title",
          "Value":  "[PRO-1847] Review Test Sets"
        },
        {
          "ReferenceName":  "Microsoft.VSTS.Common.Priority",
          "Value":  ""
        },
        {
          "ReferenceName":  "Microsoft.VSTS.Common.ClosedDate",
          "Value":  "2020-07-21T11:51:27"
        },
        {
          "ReferenceName":  "System.Description",
          "Value":  "<img src=\"https://jira.domain.de/secure/attachment/39350/39350_image-2020-07-14-15-38-48-581.png\" style=\"border: 0px solid black\"/><"
        },
        {
          "ReferenceName":  "System.State",
          "Value":  "To Do"
        }
      ],
      "Links":  [
        {
          "Change":  0,
          "TargetOriginId":  "PRO-590",
          "TargetWiId":  0,
          "WiType":  "System.LinkTypes.Hierarchy-Reverse"
        }
      ],
      "Attachments":  [
        {
          "Change":  0,
          "FileName":  "image-2020-07-08-10-20-01-372.png",
          "Comment":  "Imported from Jira",
          "AttOriginId":  "39067",
          "FilePath":  ".\\PRO\\Attachments\\39067\\image-2020-07-08-10-20-01-372.png"
        }
      ],
      "DevelopmentLink":  null,
      "AttachmentReferences":  true
    },
    {
      "Author": "my.name@deutschebahn.com",
      "Time": "2020-07-14T15:38:49+02:00",
      "Index": 1,
      "Fields": [
      ],
      "Links": [
      ],
      "Attachments": [
        {
          "Change": 0,
          "FileName": "image-2020-07-14-15-38-48-581.png",
          "Comment": "Imported from Jira",
          "AttOriginId": "39350",
          "FilePath": ".\\PRO\\Attachments\\39350\\image-2020-07-14-15-38-48-581.png"
        }
      ],
      "DevelopmentLink": null,
      "AttachmentReferences": true
    }
  ]
}

```
2. place a image with this name .\PRO\Attachments\39350\image-2020-07-14-15-38-48-581.png
3. start wi-import.exe 

4. Go to Azure Devops, and see that 3 workitems have been created:
![image](https://github.com/user-attachments/assets/0c149cd3-32f8-45a5-84ad-8e1f817bc987)

**Tool version**
 - Version of the jira-azuredevops-migrator tool  3.0.502

**Attachments**

Please attach the following files:

- wi-import-log.txt
[wi-import-log-241220-142509.txt](https://github.com/user-attachments/files/18211272/wi-import-log-241220-142509.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment] 2024-12-21 17:47
Duplicate of https://github.com/solidify/jira-azuredevops-migrator/issues/602

**Closed by Alexander-Hjelm** 2024-12-21 17:47 UTC
