### ISSUE TITLE
Error, failed to import revisions

### ISSUE THREAD

**Issue by dan-miller** [solidify/jira-azuredevops-migrator#71] opened 2019-08-09 17:20 UTC
When running a recent import, many of the work item revisions showed this error:

```
[E][13:17:07] Failed to import revisions for '1232973'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException] Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: TF237121: Cannot complete the operation. An unexpected error occurred.

Technical information (for administrator):
VS402625: Dates must be increasing with each revision.
   ---> System.Web.Services.Protocols.SoapException: VS402625: Dates must be increasing with each revision.
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.WorkItemServer.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi)
```

Looking through the Jira issues that triggered this error, I have not been able to find the cause of this. Do you have any thoughts or suggestions?

**Comment by MOlausson** [comment] 2019-08-09 20:14
@dan-miller can you share one of the files you are having trouble with?

**Comment by dan-miller** [comment] 2019-08-12 14:40
[PRJ-123-scrubbed.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3492988/PRJ-123-scrubbed.zip)

**Comment by quadmig** [comment] 2019-08-20 20:55
I am having a similar problem.  I had a config file that was working a few weeks ago and now without any changes it is giving me this error.  

I tried using the sample config instead (and just updating the top area) and I still get this error message.  It's possible this started after the Sprint 156 Update of ADO.

Failed to import revisions for '0'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException] Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: There is a problem on the server. Contact your Team Foundation Server administrator. ---> System.Web.Services.Protocols.SoapException: VS403417: ChangedBy value cannot be empty when BypassRules is specified
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.WorkItemServer.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi): 
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi)

**Comment by hqaffesha-acacustech** [comment] 2019-08-21 07:58
I managed to fix the issue, on the Agent.cs go to ImportRevision function and the following code to the try-catch at line 822: 
```
     finally
            {
                System.Threading.Thread.Sleep(10);
            }
```


it seems that the issue was happening because of the short time between each revision insert so it should wait a while before inserting the next one.

**Comment by MOlausson** [comment] 2019-08-21 08:02
Thanks for the details @quadmig and @dan-miller. I've tested importing your files and it worked ok on my Azure DevOps account. Will review @hqaffesha-acacustech comment to see if that's the root cause but great if you give it a try to see if it works for you.

**Comment by quadmig** [comment] 2019-08-21 15:25
@MOlausson , thanks for the response.  Unfortunately, the @hqaffesha-acacustech  comment did not solve the issue for me.  However, it appears the cause of my problem was that the work item type I was trying to import as had been disabled on the ADO server.  It is working now.  Thank you.

**Comment by MOlausson** [comment] 2019-08-21 18:52
@quadmig happy to hear you got passed this issue! I do also think we're on to something timing related, I'll review the code and see if it makes sense to add retries for some error conditions. Thanks @hqaffesha-acacustech for spotting this.

**Comment by MOlausson** [comment] 2019-11-29 19:26
Added retry logic on certain errors to the backlog. Closing this issue.

**Closed by MOlausson** 2019-11-29 19:26 UTC
