### ISSUE TITLE
JIRA links are not getting attached in Azure devops link's section 

### ISSUE THREAD

**Issue by saritar23** [solidify/jira-azuredevops-migrator#116] opened 2019-11-08 10:20 UTC
I am trying to export Epic(Parent)and Stories(Child) from JIRA for that I am using 
 {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },  

In link map section. 
Its showing me below details in comment section but not adding them into the links section. 
Added link(s): [Added] A-4935/-1->A-5105/-1 [System.LinkTypes.Hierarchy-Reverse]
I am using scrum template for export and Import.

**Comment by prashanthbv12** [comment] 2019-11-09 09:15
Try adding this "epic-link-field": "Epic Link",

**Comment by MOlausson** [comment] 2019-11-09 15:39
@saritar23 make sure you check your mapping coniguration like @prashanthbv12 suggests. I've checked that the [sample file](https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/Samples/config-scrum.json) works as expected with the OOB processes in Jira and Azure DevOps. Check the epic-link-field, link-map and type-map sections.

**Comment by MOlausson** [comment] 2019-11-15 19:31
@saritar23 closing this now since we cannot reproduce the error, all seems to work as expected. Feel free to reopen and add a repo if you don't agree.

**Closed by MOlausson** 2019-11-15 19:31 UTC
