### ISSUE TITLE
 Unable to connect to the remote server

### ISSUE THREAD

**Issue by Nastya85944** [solidify/jira-azuredevops-migrator#207] opened 2020-03-29 11:30 UTC
Hi,
I want to migrate items from Jira version 6.4.11 to Azure Devops.
I ran export command: jira-export -u Username -p Password--url https://yourinstance.atlassian.com --config config.json --force.

I got the next error:
_[I][13:05:23] Connecting to Jira...
[I][13:05:23] Retrieving Jira fields...
[E][13:05:25] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Error Message: Unable to connect to the remote server
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
---> (Inner Exception #0) System.InvalidOperationException: Error Message: Unable to connect to the remote server
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
[I][13:05:25] Export complete. Exported 0 items (1 errors, 0 warnings) in 00:00:02._

**Comment by madkoo** [comment] 2020-03-30 08:13
@Nastya85944 at first glance this seems to be a duplicate of #205. 
Have you verified you have the right access?

**Comment by Nastya85944** [comment] 2020-03-30 09:43
The access is right.
Does the plugin suport a migration for Jira version 6.4?

**Comment by Nastya85944** [comment] 2020-03-31 07:49
Hello,
Now I have an Authentication issue:
[I][18:36:03] Connecting to Jira...
[I][18:36:03] Retrieving Jira fields...
[E][18:36:13] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Response Content: <html>
<head>
    <title>Forbidden (403)</title>
  

Can somebody help me out on this?

**Comment by madkoo** [comment] 2020-04-16 11:26
@Nastya85944 Yes, version 6.4 is supported. 
This seems like an authentication failure that you have. Verify your access to Jira server.

**Comment by madkoo** [comment] 2020-04-22 06:06
@Nastya85944 Closing issue due to no response. If you still have problems feel free to reopen or create a new issue.

**Closed by madkoo** 2020-04-22 06:06 UTC
