### ISSUE TITLE
Epic link not added for original issue (revision 0)

### ISSUE THREAD

**Issue by Jbekker** [solidify/jira-azuredevops-migrator#862] opened 2023-09-25 10:49 UTC
**Describe the problem**
When an issue is linked to an Epic in the original issue (not through a changelog), the link is not added anymore since 3.0.159. This has something to do with the fact that fields are now added to the fields dictionary with their 'CustomFieldName' instead of the 'CustomFieldId'.

It works when I change the below line and  pass in _config.EpicLinkField but I don't know if there it a better solution for this :-)
https://github.com/solidify/jira-azuredevops-migrator/blob/e023e826fd44f3613e329b7645cd2a4ce318b49b/src/WorkItemMigrator/JiraExport/JiraMapper.cs#L249

Also, I think that would break the case for adding the epic links from the change history because that is using the custom field id instead of the name.

**Tool version**
 - Broken since 3.0.159, I verified that 3.0.139 was still working correctly.

**Comment by Jbekker** [comment] 2023-09-25 10:54
Side note, the GitHub action to sync the issue to Azure Boards is broken due to an expired PAT token

**Comment by Alexander-Hjelm** [comment] 2023-09-25 13:13
Yep, you are correct. Not sure why we would fetch the EpicLink field from jira when we should be getting it from the user config. I will fix this asap.

**Comment by Alexander-Hjelm** [comment] 2023-09-25 13:14
> Side note, your GitHub action to sync the issue to Azure Boards is broken due to an expired PAT token

This sync hasn't been used in ages :D

**Comment by Jbekker** [comment] 2023-09-25 13:29
> > Side note, your GitHub action to sync the issue to Azure Boards is broken due to an expired PAT token
> 
> This sync hasn't been used in ages :D

I was getting an email about it, maybe disable it to avoid confusion?

**Comment by Alexander-Hjelm** [comment] 2023-09-25 17:21
Strange, why would you get an email about it? Is it because the issue author has notifications on by default perhaps?

I disabled the sync until further notice. Likely we don't need it anymore since we manage issues via github now.

**Comment by aakash-pinc** [comment] 2023-10-03 16:30
Any tentative date when this will be fixed?  Linking is not working in the latest version.

**Comment by Alexander-Hjelm** [comment] 2023-10-04 11:18
@aakash-pinc, I will look at it during this week. I've had other pressing issues to deal with in the meantime :)

**Comment by palitshubhankar** [comment] 2023-10-11 00:39
Tried the new version 3.0.229. The linking is still not working for Epics and stories. Date issues are fixed.

**Comment by Alexander-Hjelm** [comment] 2023-10-11 08:29
I have noted that the Epic Links is still present. I will work on finding a fix as soon as time permits :)

**Comment by Alexander-Hjelm** [comment] 2023-10-13 08:30
Created PR https://github.com/solidify/jira-azuredevops-migrator/pull/883 with @Jbekker 's suggested fix. Could someone try the following build of the JiraExporter and verify that the problem is solved?

[Debug.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12891246/Debug.zip)

// Alexander

**Comment by Jbekker** [comment] 2023-10-16 11:24
@Alexander-Hjelm, we've tested two scenario's:
1. A issue with an epic attached on the original issue.
2. A issue without an epic attached and add the epic afterwards (changelog flow)

In both cases the exported issues had the expected link to the epic.

**Comment by Alexander-Hjelm** [comment] 2023-10-17 21:55
The issue stems from a behavior in certain versions of Jira Server where an issue that was created with an epic parent/child will have the issuelink relationship, but the History tab and the Changelog will show no information about the link.

The solution would be to augment the Rest api call in JiraProvider.cs: L310, to the following:

`https://solidifydemo.atlassian.net/rest/api/2/issue/AGILEDEMO-36?expand=changelog,renderedFields&fields=created,issuelinks`

An example response would look like this. Now we can get the links from the fields.issuelinks property and add them after going through all revisions, only if the same link has not previously been added.

```json
{
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    "id": "10193",
    "self": "https://solidifydemo.atlassian.net/rest/api/2/issue/10193",
    "key": "AGILEDEMO-36",
    "renderedFields": {
        "created": "Today 10:26 PM",
        "issuelinks": null
    },
    "changelog": {
        "startAt": 0,
        "maxResults": 4,
        "total": 4,
        "histories": [
            {
                "id": "11065",
                "author": {
                    "self": "https://solidifydemo.atlassian.net/rest/api/2/user?accountId=6038bfcc25b84e00696240d3",
                    "accountId": "6038bfcc25b84e00696240d3",
                    "emailAddress": "alexander.hjelm@solidify.dev",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "24x24": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "16x16": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "32x32": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png"
                    },
                    "displayName": "Alexander Hjelm",
                    "active": true,
                    "timeZone": "Europe/Berlin",
                    "accountType": "atlassian"
                },
                "created": "2023-10-17T22:31:47.125+0200",
                "items": [
                    {
                        "field": "Link",
                        "fieldtype": "jira",
                        "from": null,
                        "fromString": null,
                        "to": "AGILEDEMO-37",
                        "toString": "This issue Is related to AGILEDEMO-37"
                    }
                ]
            },
            {
                "id": "11064",
                "author": {
                    "self": "https://solidifydemo.atlassian.net/rest/api/2/user?accountId=6038bfcc25b84e00696240d3",
                    "accountId": "6038bfcc25b84e00696240d3",
                    "emailAddress": "alexander.hjelm@solidify.dev",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "24x24": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "16x16": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "32x32": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png"
                    },
                    "displayName": "Alexander Hjelm",
                    "active": true,
                    "timeZone": "Europe/Berlin",
                    "accountType": "atlassian"
                },
                "created": "2023-10-17T22:30:07.974+0200",
                "items": [
                    {
                        "field": "Epic Link",
                        "fieldtype": "custom",
                        "fieldId": "customfield_10008",
                        "from": "10106",
                        "fromString": "AGILEDEMO-15",
                        "to": null,
                        "toString": ""
                    }
                ]
            },
            {
                "id": "11062",
                "author": {
                    "self": "https://solidifydemo.atlassian.net/rest/api/2/user?accountId=6038bfcc25b84e00696240d3",
                    "accountId": "6038bfcc25b84e00696240d3",
                    "emailAddress": "alexander.hjelm@solidify.dev",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "24x24": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "16x16": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "32x32": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png"
                    },
                    "displayName": "Alexander Hjelm",
                    "active": true,
                    "timeZone": "Europe/Berlin",
                    "accountType": "atlassian"
                },
                "created": "2023-10-17T22:30:07.957+0200",
                "items": [
                    {
                        "field": "IssueParentAssociation",
                        "fieldtype": "jira",
                        "from": "10106",
                        "fromString": "AGILEDEMO-15",
                        "to": null,
                        "toString": null
                    }
                ]
            },
            {
                "id": "11059",
                "author": {
                    "self": "https://solidifydemo.atlassian.net/rest/api/2/user?accountId=6038bfcc25b84e00696240d3",
                    "accountId": "6038bfcc25b84e00696240d3",
                    "emailAddress": "alexander.hjelm@solidify.dev",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "24x24": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "16x16": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png",
                        "32x32": "https://secure.gravatar.com/avatar/e57bc21be69a2940bfa10a99ab4f6d74?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAH-1.png"
                    },
                    "displayName": "Alexander Hjelm",
                    "active": true,
                    "timeZone": "Europe/Berlin",
                    "accountType": "atlassian"
                },
                "created": "2023-10-17T22:26:03.890+0200",
                "items": [
                    {
                        "field": "IssueParentAssociation",
                        "fieldtype": "jira",
                        "from": null,
                        "fromString": null,
                        "to": "10106",
                        "toString": "AGILEDEMO-15"
                    }
                ]
            }
        ]
    },
    "fields": {
        "created": "2023-10-17T22:26:03.805+0200",
        "issuelinks": [
            {
                "id": "10099",
                "self": "https://solidifydemo.atlassian.net/rest/api/2/issueLink/10099",
                "type": {
                    "id": "10201",
                    "name": "Related",
                    "inward": "Is related to",
                    "outward": "Is related to",
                    "self": "https://solidifydemo.atlassian.net/rest/api/2/issueLinkType/10201"
                },
                "outwardIssue": {
                    "id": "10194",
                    "key": "AGILEDEMO-37",
                    "self": "https://solidifydemo.atlassian.net/rest/api/2/issue/10194",
                    "fields": {
                        "summary": "(Jira smoke tests) epic with child set on first revision",
                        "status": {
                            "self": "https://solidifydemo.atlassian.net/rest/api/2/status/10000",
                            "description": "",
                            "iconUrl": "https://solidifydemo.atlassian.net/",
                            "name": "To Do",
                            "id": "10000",
                            "statusCategory": {
                                "self": "https://solidifydemo.atlassian.net/rest/api/2/statuscategory/2",
                                "id": 2,
                                "key": "new",
                                "colorName": "blue-gray",
                                "name": "To Do"
                            }
                        },
                        "priority": {
                            "self": "https://solidifydemo.atlassian.net/rest/api/2/priority/3",
                            "iconUrl": "https://solidifydemo.atlassian.net/images/icons/priorities/medium.svg",
                            "name": "Medium",
                            "id": "3"
                        },
                        "issuetype": {
                            "self": "https://solidifydemo.atlassian.net/rest/api/2/issuetype/10000",
                            "id": "10000",
                            "description": "A big user story that needs to be broken down. Created by Jira Software - do not edit or delete.",
                            "iconUrl": "https://solidifydemo.atlassian.net/images/icons/issuetypes/epic.svg",
                            "name": "Epic",
                            "subtask": false,
                            "hierarchyLevel": 1
                        }
                    }
                }
            }
        ]
    }
}
```

**Closed** 2023-10-18 09:53 UTC
Labels: bug

**Comment by timakamystery** [comment] 2023-11-14 18:54
can a new build be provided pls ?

**Comment by Alexander-Hjelm** [comment] 2023-11-15 07:34
@timakamystery New release here: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.250
