### ISSUE TITLE
Import Comments Showing Jira html style tags

### ISSUE THREAD

**Issue by GBRacerX1** [solidify/jira-azuredevops-migrator#764] opened 2023-04-27 14:41 UTC
After exporting and importing from jira cloud the description is rendered properly in DevOps but Comments each have the following at the top of each comment along with the comment:
<style> div { display:block; } table.confluenceTable { border-collapse:collapse; margin:5px 0 5px 2px; width:auto; } table { display:table; border-collapse:separate; border-spacing:2px; border-color:grey; } tbody { display:table-row-group; vertical-align:middle; border-color:inherit; } tr { display:table-row; vertical-align:inherit; border-color:inherit; } th.confluenceTh { border:1px solid #ccc; background:#f5f5f5; padding:3px 4px; text-align:center; } th { font-weight:bold; text-align:-internal-center; } td, th { display:table-cell; vertical-align:inherit; } td.confluenceTd { border:1px solid #ccc; padding:3px 4px; } dfn, cite { font-style:italic; } </style>
PR to move review environment

When clicking edit in the comment the style part will disappear and only the comment will remain.

**Tool version**
.115

			{
				"source": "comment",
				"target": "System.History",
				"mapper": "MapRendered"
			},

**Comment by Alexander-Hjelm** [comment] 2023-05-16 07:42
Not sure why that could be. Looks like you have some kind of confluence table in the description of your source issue, and the migrator maybe doesn't know what to make of that?

**Comment by sgtwilko** [comment] 2023-05-22 19:46
We also see this, and there's no confluence table, it would just seem that comments in DevOps cannot accept style blocks, only inline style.

**Comment by Alexander-Hjelm** [comment] 2023-05-23 07:18
That would probably make sense. In that case this would just be a limitation in ADO. Not sure at the moment what to do about it. A possible mitigation would be to regex search and cut out and style blocks.

Marking as feature request.

**Comment by jus062** [comment] 2023-06-02 03:49
I'm currently testing the latest version of the tool and can confirm it happens for us as well. As an FYI, I did a migration in March using version 2.3.117 to the same Devops server and worked fine. So definitely something different in v3.x

**Comment by Alexander-Hjelm** [comment] 2023-06-03 19:58
Probably related to the upgrade from the old work item tracking API library to Microsoft.TeamFoundationServer.Client then. I will look into it as soon as time allows, but currently there are other bugs that are higher in priority.

Any additional information that could aid in reproducing the issue would be much appreciated.

**Comment by jus062** [comment] 2023-06-04 22:45
Hi Alex,

On further investigation, I don't believe it is an issue with your tool. If you turn off the New Board Hub preview, it works fine. I noticed this a week or so back with a tool that integrates between devops and another vendor. I raised a bug with them which they are now investigating.

However, I have gone back to review items that we migrated in April using v2.3x which was fine, and are now showing the same markup. I think it might be due to a change in Devops either in Sprint 220 or 221.

**Comment by Alexander-Hjelm** [comment] 2023-06-05 07:55
Yeah I know that there currently is incompatibility with the New Boards Hub feature.

See:

https://github.com/solidify/jira-azuredevops-migrator/issues/607

**Comment by jus062** [comment] 2023-06-08 00:14
Is it possible to force Comments as plain text instead?

**Comment by GBRacerX1** [comment] 2023-06-08 00:45
I wound up stripping all the bad info from the comments using notepad + or similar tool  I saw 2 patterns and deleted both from all the fileds and then ran the import.

From: jus062 ***@***.***>
Date: Wednesday, June 7, 2023 at 8:14 PM
To: solidify/jira-azuredevops-migrator ***@***.***>
Cc: George Bicking ***@***.***>, Author ***@***.***>
Subject: Re: [solidify/jira-azuredevops-migrator] Import Comments Showing Jira html style tags (Issue #764)

Is it possible to force Comments as plain text instead?

**Comment by jus062** [comment] 2023-06-08 01:01
Interesting and thanks for that. I'll have a look and see if that is viable. Thankfully there are only a small number of tickets (~160 or so), so not that painful.

**Comment by jus062** [comment] 2023-06-08 01:04
Thanks again. Will do that.

**Comment by jus062** [comment] 2023-06-15 23:42
I've heard back from Microsoft overnight who have confirmed it is an issue at their end. Apparantly a fix has been done but not yet released.

**Comment by RoyalWulf** [comment] 2023-07-07 04:06
> I've heard back from Microsoft overnight who have confirmed it is an issue at their end. Apparantly a fix has been done but not yet released.

Can you tell me who you were talking to at Microsoft? When I asked about this issue they didn't seem to know about it. Do you have a Microsoft bug number or issue number?

**Comment by jus062** [comment] 2023-07-07 04:12
I raised it on the developer community

https://developercommunity.visualstudio.com/t/HTML-markup-showing-in-comments-migrated/10383247

Relevant bit is here

<img width="479" alt="image" src="https://github.com/solidify/jira-azuredevops-migrator/assets/94574483/3079c3a2-af09-48c6-99fd-259606cde02b">

**Comment by RoyalWulf** [comment] 2023-07-07 04:17
Thank you, I have passed this onto my Microsoft contact.

**Comment by alfreddevries** [comment] 2023-08-31 11:08
Hi @Alexander-Hjelm ,

Any news on this.

It concurrence fields on which "Wiki Style Render" is enabled in Jira .

When I clean up the Export .json files by removing the <style>...</style> block the content imported is still formatted correctly.

Rather not do the extra step cleaning up

Regards Alfred

**Comment by Alexander-Hjelm** [comment] 2023-08-31 11:18
@alfreddevries Good catch! Could you advise us on how to enable Wiki Style Render for a field in Jira?

**Comment by alfreddevries** [comment] 2023-08-31 11:36
Hi @Alexander-Hjelm,

You can find instructions [here](https://qmetrysupport.atlassian.net/servicedesk/customer/portal/2/topic/8ef38f03-1fcd-47e9-995a-79be83f85f6d/article/720207914)

Regards Alfred

**Comment by Alexander-Hjelm** [comment] 2023-08-31 11:59
It seems our test environment is already configured to use Wiki Style Render for the description field:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/077e1bf6-c5de-4c74-ad10-fdba9cae772d)

So we are still unable to reproduce the bug.

Are there any other configurations you've made that you are aware of, which could impact the tool?

**Comment by Alexander-Hjelm** [comment] 2023-08-31 18:23
@alfreddevries Ok! So am I correct in my understanding that your description field renders as expected, but the comments get malformatted?

**Comment by RoyalWulf** [comment] 2023-08-31 21:27
Microsoft say they have fixed this issue:
https://developercommunity.visualstudio.com/t/HTML-markup-showing-in-comments-migrated/10383247
it has not been released yet

**Comment by Alexander-Hjelm** [comment] 2023-08-31 22:47
Could it be an idea to try disabling the New Board Hub features for an Azure DevOps project for the purpose of testing the migration, then switching it on again? Given that this does not impact your other business activities, of course.

**Comment by RoyalWulf** [comment] 2023-08-31 23:19
Not sure how that works.
If I am in Azure DevOps, if i disable New Board Hub then Comments look good. If I enable New Board Hub then Comments have the embed codes.
Are you asking that I try disabling New Board Hub, then run the import then enable New Board Hub?
My thoughts are that it is a bug in Azure DevOps New Board Hub feature and Microsoft say they have fixed it but not released the fix.

**Comment by Alexander-Hjelm** [comment] 2023-09-01 06:09
Ok! So the formatting is correct if you disable New Board Hub features but not correct as soon as you enable it? Not sure what to make of thata, whether it is indeed a bug in Azure DevOps or something we should try and patch away on our end.

**Comment by alfreddevries** [comment] 2023-09-01 06:36
Same goes for me, good find hadn't thought of that.

All though I would like to ask what the reason is for adding the <style>...</style> block.

In FieldMapperUitls.cs line 126 call to CorrectRenderedHtmlvalue and def of CorrectRenderedHtmlvalue at line 177 the resource JiraExport.jirastyles.css is Read and prefixed to the htmlValue om  line 201.

It 's the exact code that appears in the .json of MapRender fields. I found the "css" in jirastyle.css file in the JiraExport folder.

Regards Alfred

**Comment by Alexander-Hjelm** [comment] 2023-09-01 07:43
@alfreddevries Correct, that would be these lines it seems:

https://github.com/solidify/jira-azuredevops-migrator/blob/54ac55c5dbc0ab15064f0db08152465c1bc6dc6e/src/WorkItemMigrator/JiraExport/RevisionUtils/FieldMapperUtils.cs#L197C1-L201C70

Not sure myself why it needs to be there since formatting isn't migrated anyway. The senior devs will need to answer that.

I can try and add a configuration flag which controls this behavior if that would solve your problem. It makes sense to me to at least make this feature optional.

I will work on a patch ASAP. I will upload a binary in this issue thread for you to try. It would be great if you could try it and let me know if your issue was resolved or not :)

I will probably be back later today, so keep an eye out!

**Comment by alfreddevries** [comment] 2023-09-01 07:47
Hi @Alexander-Hjelm,

That would be great, love to help out.

No Problem, nothing's bleeding ;)

Regards Alfred

**Comment by Alexander-Hjelm** [comment] 2023-09-01 10:11
@alfreddevries Try this distribution.
[Debug-feature-optional-jira-css-style.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12496871/Debug-feature-optional-jira-css-style.zip)

Not that you will need to set the following flag on the top level of your config:

```json
"include-jira-css-styles": false,
```

**Comment by alfreddevries** [comment] 2023-09-01 13:13
HI Alexander,

The Switch include-jira-css-styles set to (false/true) work both perfectly. So is the result of the Import when set to false

BTW You can see the html code after import in the Queries view on Azure Boards, you will need to add the columns Description and History and New Board Hubs should be enabled. So there are a view places in Azure Boards that are affected in the New Feature

Regards Alfred

Sent from Mail for Windows

**Comment by alfreddevries** [comment] 2023-09-01 14:10
No, I meant to report that the switch works both ways. Export contains css or not

The Import when the switch is set to false solves the issue for both fields Description and History and for the New Board Hubs feature.

Thanks for considering merging the change

Regards Alfred

**Comment by Alexander-Hjelm** [comment] 2023-09-01 14:13
Aha, perfect then! :D

Let me merge and release a new public version with the completion of the interation tests.

Thanks for sniffing out the issue!

**Closed** 2023-09-01 14:28 UTC
Labels: enhancement

**Comment by RoyalWulf** [comment] 2023-09-03 21:05
I have already migrated 20000 Jira issues with this in them so i hope MS fixes it

**Comment by RoyalWulf** [comment] 2023-10-15 21:27
@Alexander-Hjelm do you know if this is going to be fixed my MS?

**Comment by jus062** [comment] 2023-10-15 22:46
I raised it with MS months ago and was told it had been fixed. Either they are fibbing or it is not yet released. Probably the latter but very annoying.
________________________________

**Comment by RoyalWulf** [comment] 2023-10-15 22:48
I raised it with them too. I wonder if it has been fixed for new migrations? I haven't migrated anything lately.  My worry is they are rolling out the feature so we wont be able to turn it off.

**Comment by timakamystery** [comment] 2023-12-19 16:25
css code in the comments got fixed for me by disabling 'New Board Hubs feature' as per: https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-202-update#new-boards-hubs-now-available-in-public-preview

**Comment by jus062** [comment] 2023-12-19 21:45
That's not really a viable solution as at some point next year, that is all you will be able to use.

[cid:8498bd2b-b266-49ba-bed3-0ada69ead65d]
________________________________
