### ISSUE TITLE
Error when importing into Aure DevOps. 

### ISSUE THREAD

**Issue by DanteOnePlusOne** [solidify/jira-azuredevops-migrator#759] opened 2023-04-20 15:18 UTC
Error when importing into Aure DevOps. 
If changes were made to the custom field, then there are multiple revisions of the field value.    

[I][15:38:28] Import started. Importing 1 items with 7 revisions.
[I][15:38:28] Processing 1/7 - wi '1711', jira 'ITXTP-653, rev 0'.
[I][15:38:29] Processing 2/7 - wi '1711', jira 'ITXTP-653, rev 1'.
[I][15:38:29] Processing 3/7 - wi '1711', jira 'ITXTP-653, rev 2'.
[E][15:38:29]VS403691: Update to work item 1711 had two or more updates for field with reference name 'Custom.Ort'. A field cannot be updated more than once in the same update.

And only the value of the field for the first revision is imported, and the other values are ignored. How can I make it so that the values of the last (maximum) revision are imported?
Thank you.

Here is part of config file

"field-map": {
    "field": [
         {
        "source": "Ort",
        "source-type": "name",
        "target": "Ort",
       },

Here is example of importing file

OriginId": "ITXTP-653",
  "WiId": -1,
  "Revisions": [
    {
      "Author": "o@it.com",
      "Time": "2023-04-20T13:40:04.346+02:00",
      "Index": 0,
      "Fields": [
         {
          "ReferenceName": "Ort",
          "Value": "TesOrt1"
        },  
{
      "Author": "o@it.com",
     "Time": "2023-04-20T13:40:52.351+02:00",
      "Index": 2,
      "Fields": [
        {
          "ReferenceName": "Ort",
          "Value": "TesOrt2"
        }

**Comment by Alexander-Hjelm** [comment] 2023-04-21 12:46
> Update to work item 1711 had two or more updates for field with reference name 'Custom.Ort'.

This message typically means that a single revision has multiple patches of the same field, which is not allowed in ADO.

Check if this could be the case?

**Comment by DanteOnePlusOne** [comment] 2023-04-21 14:14
Hi. Thanks for the quick response. 
As I understand it, in this sample piece of the imported file, the Orth field has two values. The first is for revision with index 0, and the second is for revision with index 2. This field is not repeated in each individual revision.
As a result, an error occurs when importing the second revision.

OriginId": "ITXTP-653",
"WiId": -1,
"Revisions": [
{
"Author": "[o@it.com](mailto:o@it.com)",
"Time": "2023-04-20T13:40:04.346+02:00",
"Index": 0,
"Fields": [
{
"ReferenceName": "Ort",
"Value": "TesOrt1"
},
{
"Author": "[o@it.com](mailto:o@it.com)",
"Time": "2023-04-20T13:40:52.351+02:00",
"Index": 2,
"Fields": [
{
"ReferenceName": "Ort",
"Value": "TesOrt2"
}

**Comment by Alexander-Hjelm** [comment] 2023-04-22 08:29
Ok! Will have to look into that as soon as time permits.

Marking as bug

**Comment by DanteOnePlusOne** [comment] 2023-04-22 09:11
I founded out, that It's only happens when no mapping, or (default) mapping. But I cannot find relevant mapping for my custom field (it's one row string).

**Comment by Alexander-Hjelm** [comment] 2023-04-23 09:56
See the FAQ for mapping custom string fields: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field-by-name

**Comment by DanteOnePlusOne** [comment] 2023-04-23 10:15
With this mapper I have described above problem

Example:

{
    "source": "CustomFieldName",
    "source-type": "name",
    "target": "Microsoft.VSTS.TCM.ReproSteps"
}

And with this mapper runs better (no duplicates), but it needs multi row string field type
{
    "source": "description",
    "target": "Microsoft.VSTS.TCM.ReproSteps",
    "mapper":"MapRendered"
}

**Comment by Alexander-Hjelm** [comment] 2023-04-23 10:17
MapRendered is meant for fields with html contents, like Description and ReproSteps :)

**Comment by Alexander-Hjelm** [comment] 2023-05-26 08:13
Issue reported separately through support mailbox. See email from Miroslav Koutny (CZ), Thu 5/25/2023 7:12 PM

**Comment by Alexander-Hjelm** [comment] 2023-10-04 11:36
[Miroslav Koutny]

Well I did a deep research to find the root cause and it's interesting that it's always related to the same pattern.

1. In one revision you either set up new values, or update the values to multiple fields 
2. These values are from pickup list JIRA source
3. These pickuplists are migrated to CUSTOM pickup list to ADO and those pickup lists in ADO are Mandatory 

If I work only with the text fields on the ADO side the problem is not happening.

So my conclusion is , that it might be a side effect of custom pickup lists, or something like that may be improper configuration of that fields in ADO.

**Comment by Alexander-Hjelm** [comment] 2023-11-28 07:33
@DanteOnePlusOne , @JocaJovan , I noticed that your field reference names actually look very strange. ("Ort" and "GDPR relevant"). For ADO Services, the built-in field reference names usually start with "System." or "Microsoft.". Custom fields usually start with "Custom", and they cannot contain spaces if I'm not mistaken. Can you try and ensure that your have specified the **field reference name** and not the **field name**?

Here is an index of all the built-in fields: https://learn.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=azure-devops

**Comment by Alexander-Hjelm** [comment] 2023-11-29 14:06
Issue has been resolved by Miroslav Koutnry. The root cause turned out to be incorrect configuration on the user's side.

I have documented the solution as part our our troubleshooting guidelines in the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#troubleshooting-i-receive-errors-like-vs403691-update-to-work-item-165-had-two-or-more-updates-for-field-with-reference-name-customxxx-a-field-cannot-be-updated-more-than-once-in-the-same-update

Closing the issue. Please reopen the issue and tag me if the problem persists.

**Closed by Alexander-Hjelm** 2023-11-29 14:06 UTC
Labels: bug
