### ISSUE TITLE
FieldDefinitionNotExistException because of ReproSteps

### ISSUE THREAD

**Issue by SukramAbAnvil** [solidify/jira-azuredevops-migrator#23] opened 2019-02-07 17:55 UTC
I have migrated a project with the "Sample config" as a test, only the project names and the Jira query have been changed.
The  jira export seem to work fine, but during the import I get the above mentioned exception.

**Comment by SukramAbAnvil** [comment] 2019-02-07 18:10
Based on my analysis, the problem is the following code passage:
[Jira Mapper Line 367](https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraMapper.cs)

`{ WorkItemType.Task, MergeMapping(commonFields, bugFields, taskFields) },`

The type "task" get also the fields of a bug because of the merge.

I mean the following code should fix the problem:
`{ WorkItemType.Task, MergeMapping(commonFields, taskFields) },`

What do you think?

**Comment by MOlausson** [comment] 2019-02-16 15:48
Hi @SukramAbAnvil, Appologies for not geting back sooner. We've had a look at this and it seems to be caused by code that's not supposed to be there anymore. We're working on an update with the same intent as your PR.

**Comment by MOlausson** [comment] 2019-03-22 00:37
We ended up not doing more changes that this at the moment so thanks for your fix for this specific issue.

**Closed by MOlausson** 2019-03-22 00:37 UTC
