### ISSUE TITLE
is jira custom field type option supported?

### ISSUE THREAD

**Issue by quadmig** [solidify/jira-azuredevops-migrator#72] opened 2019-08-21 19:43 UTC
I have been trying to export a jira custom field but I cannot get it to work.  It is a dropdown field in Jira with type "option" where the user selects 1 of the options presented. 

I was able to get a different custom field to work; just not any of the ones that we have of type "option."

If I put it in the config file, the export ignores it entirely.  The field is not contained in the exported file or export log.

**Comment by quadmig** [comment] 2019-08-21 19:43
Here is the config info:
{
        "source": "customfield_13555", 
        "target": "Custom.QuadPriority",
}


Here is the field info from Jira.
"customfield_13555":{"required":false,"schema":{"type":"option","custom":"com.atlassian.jira.plugin.system.customfieldtypes:select","customId":13555},"name":"ITSD-Quad Priority","hasDefaultValue":false,"operations":["set"],"allowedValues":[{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16482","value":"1","id":"16482"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16483","value":"2","id":"16483"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16484","value":"3","id":"16484"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16485","value":"4","id":"16485"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16486","value":"5","id":"16486"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16487","value":"6","id":"16487"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16488","value":"7","id":"16488"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16489","value":"8","id":"16489"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/16490","value":"9","id":"16490"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/17215","value":"0","id":"17215"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/17218","value":"x","id":"17218"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/17219","value":"-","id":"17219"},{"self":"https://ourjiraurl/rest/api/2/customFieldOption/17221","value":"None","id":"17221"}]}

**Comment by nicksimons-limeade** [comment] 2019-08-28 21:15
@MOlausson is there any workaround for mapping custom fields?

**Comment by AmitNaveh23** [comment] 2019-08-29 13:09
+1 also happens to me

**Comment by quadmig** [comment] 2019-08-29 13:28
I am using version 2.2.31.

I am able to export this custom field, but it is just a string, not a dropdown option.

{
        "source": "customfield_15050",
        "target": "Custom.URL"
		
      },

{"id":"customfield_15050","name":"ITSD-Quad URL","custom":true,"orderable":true,"navigable":true,"searchable":true,"clauseNames":["cf[15050]","ITSD-Quad URL"],"schema":{"type":"string","custom":"com.atlassian.jira.plugin.system.customfieldtypes:url","customId":15050}}

**Comment by MOlausson** [comment] 2019-09-10 16:57
I'll try to repro, it is supposed to work. Can you see if adding a "mapper": "MapArray" element to the field mapping helps.

**Comment by quadmig** [comment] 2019-09-10 17:25
@MOlausson, that did not change anything.  It still ignores the field entirely.  

On a semi-related note, it tries to map a different custom field of type array, but if only 1 value is selected in the array, the value comes up blank.  
{"ReferenceName":"Custom.MigratedEnvironment","Value":""}
If 2 values are selected, they both appear in the value separated by a semi-colon.
{"ReferenceName":"Custom.MigratedEnvironment","Value":"Production;Test"}

It maps fix version (a non-custom array) perfectly.

**Comment by prashanthbv12** [comment] 2019-09-16 12:07
Is this issue is fixed? tool is not reading values from Jira drop down fild. export log file shows blank

**Comment by prashanthbv12** [comment] 2019-09-17 05:04
@MOlausson @AmitNaveh23 Did you find any solution for this?

**Comment by mfourieshieldai** [comment] 2019-10-06 18:49
Similar issue. 
`"customfield_10052":{"self":"https://shieldai.atlassian.net/rest/api/2/customFieldOption/10017","value":"Minor","id":"10017"},`

using "mapper": "MapArray", makes no difference.

config
`      {
        "source": "customfield_10052",
        "target": "Microsoft.VSTS.Common.Severity",
        "mapper": "MapArray",
        "mapping": {
          "values": [
            {
              "source": "Critical",
              "target": "1 - Critical"
            },
            {
              "source": "Major",
              "target": "2 - High"
            },
            {
              "source": "Moderate",
              "target": "3 - Medium"
            },
            {
              "source": "Minor",
              "target": "4 - Low"
            }
          ]
        }
      },`

Looks like private List<WiField> MapFields(JiraRevision r) is not detecting the field

**Comment by mfourieshieldai** [comment] 2019-10-06 21:53
This hack fixes it, note the **type == Newtonsoft.Json.Linq.JTokenType.Object** else addition in the ExtractFields method

`                else if (type == JTokenType.Array && prop.Value.Any())
                {
                    value = string.Join(";", prop.Value.Select(st => st.ExValue<string>("$.name")).ToList());
                    if ((string)value == ";")
                        value = string.Join(";", prop.Value.Select(st => st.ExValue<string>("$.value")).ToList());
                }
                else if (type == Newtonsoft.Json.Linq.JTokenType.Object)
                {
                    if (prop.Value["value"] != null)
                    {
                        value = prop.Value["value"].ToString();
                    }
                }

                if (value != null)
                {
                    fields[name] = value;
                }`

**Comment by sgullluu** [comment] 2019-10-07 10:30
@mfourieshieldai : is it working for you?

**Comment by MOlausson** [comment] 2019-10-07 21:46
@mfourieshieldai I've checked your suggestion and it looks like the options type maps to a Json object. I'll do some more testing tomorrow and release a fix if it works out well.

**Comment by sgullluu** [comment] 2019-10-09 06:32
@MOlausson : any update on this fix?

**Comment by MOlausson** [comment] 2019-10-09 17:22
@sgullluu I went with @mfourieshieldai suggestion. Try it out and see if it works for you.

**Comment by AmitNaveh23** [comment] 2019-10-16 15:17
Also doesn't work for custom fields with type:
"custom": "com.atlassian.jira.plugin.system.customfieldtypes:userpicker"

here is an API response comparison between a user default filed (assignee) and custom user field 
[userpicker_API_comparison.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3735061/userpicker_API_comparison.txt)

**Comment by AmitNaveh23** [comment] 2019-11-07 09:59
@MOlausson any update on this one? custom fields of types "User Picker (single user)" and "Select List (multiple choices)" aren't being exported

**Comment by madkoo** [comment] 2019-12-06 12:34
Hi, @AmitNaveh23  we were not able to reproduce this issue with the latest version. Please try again with the newly released version. 
We will close this issue for now and if there are still problems let us know and we can open the issue.

**Closed by madkoo** 2019-12-06 12:34 UTC
