### ISSUE TITLE
jira-export crash

### ISSUE THREAD

**Issue by gekap** [solidify/jira-azuredevops-migrator#108] opened 2019-10-23 18:01 UTC
Hello,

I am trying to export a complicate project and jira-export.exe crashes.

The query is 
"query": "project = xxxx OR IssueFunction in LinkedIssuesOf('project = xxx') ORDER BY project ASC",

The error is 

[I][13:40:49] Processing 4151/16015 - 'xxxx-6540'.
[E][13:40:50] Unexpected migration error.
[System.Collections.Generic.KeyNotFoundException] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh):
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)

seems like a bug.

**Comment by gekap** [comment] 2019-11-04 13:31
Hello again,

I run the jira-export using debug mode and I go this line before the crash

[I][15:05:26] Processing parent issue 'xxxxx-6540'.
[D][15:05:26]    Downloaded item.
[D][15:05:27]    Link with description 'This issue is related to xxxxx-860' is either not found or this issue (xxxxx-6540) is not inward issue.
[E][15:05:27] Unexpected migration error.


Any idea how to fix this?

**Comment by MOlausson** [comment] 2019-11-06 18:00
@gekap is the second report also for a query using functions (IssueFunction in LinkedIssuesOf)? We're investigating this now and will try to repro. Are you using the ScriptRunner JQL extension (I assume so) and sure that the query return the correct result in our tool (16015 items from the first report)?

**Comment by gekap** [comment] 2019-11-07 09:30
@MOlausson I get this error with 2 configurations
1) The default one " "query": "project = xxxx ORDER BY Rank ASC" "
2) Using ScriptRunner as you saw above.

I test the query and it worked. I got all the results. Then I apply it in the configuration and on the specific issue crash again.

I tried to skip that issue and crashed on the next one with the same error.


Thank you,

**Comment by madkoo** [comment] 2019-11-14 09:59
@gekap are you using Scriptrunner on Jira Cloud or Jira Server?  
Can you provide information if the issue that it crashed had values in fields like "reporter" and "created"?

**Comment by gekap** [comment] 2019-11-15 09:08
@madkoo It does not matter if I use Scriptrunner or not. It always crash. I attach the issue which the issue appears.

[IUCVI-6524.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3850662/IUCVI-6524.zip)

**Comment by madkoo** [comment] 2019-11-18 08:13
@gekap  thank you for providing the issue json. Can you also provide the full export log for more details?

**Comment by gekap** [comment] 2019-11-18 08:39
[jira-export-log-191023-095135.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3857544/jira-export-log-191023-095135.zip)

Here is the log from the crash. It does not give much information. It's the same with the original ticket.

**Comment by madkoo** [comment] 2019-12-09 12:17
@gekap Any updates on this? Have you tried with the latest released version?

**Comment by madkoo** [comment] 2019-12-17 07:44
@gekap closing this now since we cannot reproduce the error, all seems to work as expected with the new version. Feel free to reopen if the problem still persists.

**Closed by madkoo** 2019-12-17 07:44 UTC

**Comment by timakamystery** [comment] 2024-02-13 15:04
@Alexander-Hjelm on import using latest 356 we have:
```
[E][19:01:41] Failed to import revisions for '1283951'.
[System.Collections.Generic.KeyNotFoundException] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WorkItemImport.WitClientUtils.CorrectClosedByAndClosedDate(WiRevision rev, WorkItem wi)
   at WorkItemImport.WitClientUtils.EnsureFieldsOnStateChange(WiRevision rev, WorkItem wi)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi, Settings settings): 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WorkItemImport.WitClientUtils.CorrectClosedByAndClosedDate(WiRevision rev, WorkItem wi)
   at WorkItemImport.WitClientUtils.EnsureFieldsOnStateChange(WiRevision rev, WorkItem wi)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi, Settings settings)
[I][19:01:41] Processing 22485/38401 - wi '1283951', jira 'ESRMX-4744, rev 43'.
```
got 60 such errors out of 3k imported items
